ACTIVITY_NAME_MAX_LENGTH = 50

BUILDING_ADDRESS_MAX_LENGTH = 200
BUILDING_LATITUDE_MIN_VALUE = -90.0
BUILDING_LATITUDE_MAX_VALUE = 90.0
BUILDING_LONGITUDE_MIN_VALUE = -180.0
BUILDING_LONGITUDE_MAX_VALUE = 180.0

ORGANIZATION_NAME_MAX_LENGTH = 100

PHONENUMBER_NUM_MAX_LENGTH = 16

MIN_SEARCH_RADIUS = 1
MAX_SEARCH_RADIUS = 50000
